-- Script generated by Redgate Compare v1.15.2.10683


-- deployment: Creating GetName...
CREATE PROCEDURE GetName ()
BEGIN   
        SELECT * FROM CONTACTS;
END;


-- deployment: Creating GetContacts...
CREATE PROCEDURE GetContacts ()
BEGIN   
        SELECT * FROM CONTACTS;
#V3
END;


-- deployment: Creating acc_transaction...
CREATE TABLE acc_transaction (
    TXN_ID bigint NOT NULL,
    AMOUNT float NOT NULL,
    FUNDS_AVAIL_DATE datetime NOT NULL,
    TXN_DATE datetime NOT NULL,
    TXN_TYPE_CD varchar(10) NULL,
    ACCOUNT_ID int NULL,
    EXECUTION_BRANCH_ID int NULL,
    TELLER_EMP_ID int NULL
);
ALTER TABLE acc_transaction ADD PRIMARY KEY (TXN_ID);


-- deployment: Creating acc_transaction.ACC_TRANSACTION_EMPLOYEE_FK...
CREATE INDEX ACC_TRANSACTION_EMPLOYEE_FK USING BTREE ON acc_transaction(TELLER_EMP_ID);


-- deployment: Creating acc_transaction.ACC_TRANSACTION_BRANCH_FK...
CREATE INDEX ACC_TRANSACTION_BRANCH_FK USING BTREE ON acc_transaction(EXECUTION_BRANCH_ID);


-- deployment: Creating acc_transaction.ACC_TRANSACTION_ACCOUNT_FK...
CREATE INDEX ACC_TRANSACTION_ACCOUNT_FK USING BTREE ON acc_transaction(ACCOUNT_ID);


-- deployment: Creating account...
CREATE TABLE account (
    ACCOUNT_ID int NOT NULL,
    AVAIL_BALANCE float NULL,
    CLOSE_DATE date NULL,
    LAST_ACTIVITY_DATE date NULL,
    OPEN_DATE date NOT NULL,
    PENDING_BALANCE float NULL,
    STATUS varchar(10) NULL,
    CUST_ID int NULL,
    OPEN_BRANCH_ID int NOT NULL,
    OPEN_EMP_ID int NOT NULL,
    PRODUCT_CD varchar(10) NOT NULL
);
ALTER TABLE account ADD PRIMARY KEY (ACCOUNT_ID);


-- deployment: Creating acc_transaction.ACC_TRANSACTION_ACCOUNT_FK...
ALTER TABLE acc_transaction
    ADD CONSTRAINT ACC_TRANSACTION_ACCOUNT_FK FOREIGN KEY (ACCOUNT_ID)
    REFERENCES account(ACCOUNT_ID);


-- deployment: Creating account.ACCOUNT_PRODUCT_FK...
CREATE INDEX ACCOUNT_PRODUCT_FK USING BTREE ON account(PRODUCT_CD);


-- deployment: Creating account.ACCOUNT_EMPLOYEE_FK...
CREATE INDEX ACCOUNT_EMPLOYEE_FK USING BTREE ON account(OPEN_EMP_ID);


-- deployment: Creating account.ACCOUNT_CUSTOMER_FK...
CREATE INDEX ACCOUNT_CUSTOMER_FK USING BTREE ON account(CUST_ID);


-- deployment: Creating account.ACCOUNT_BRANCH_FK...
CREATE INDEX ACCOUNT_BRANCH_FK USING BTREE ON account(OPEN_BRANCH_ID);


-- deployment: Creating employee...
CREATE TABLE employee (
    EMP_ID int NOT NULL,
    END_DATE date NULL,
    FIRST_NAME varchar(20) NOT NULL,
    LAST_NAME varchar(20) NOT NULL,
    START_DATE date NOT NULL,
    TITLE varchar(20) NULL,
    ASSIGNED_BRANCH_ID int NULL,
    DEPT_ID int NULL,
    SUPERIOR_EMP_ID int NULL
);
ALTER TABLE employee ADD PRIMARY KEY (EMP_ID);


-- deployment: Creating account.ACCOUNT_EMPLOYEE_FK...
ALTER TABLE account
    ADD CONSTRAINT ACCOUNT_EMPLOYEE_FK FOREIGN KEY (OPEN_EMP_ID)
    REFERENCES employee(EMP_ID);


-- deployment: Creating acc_transaction.ACC_TRANSACTION_EMPLOYEE_FK...
ALTER TABLE acc_transaction
    ADD CONSTRAINT ACC_TRANSACTION_EMPLOYEE_FK FOREIGN KEY (TELLER_EMP_ID)
    REFERENCES employee(EMP_ID);


-- deployment: Creating employee.EMPLOYEE_EMPLOYEE_FK...
CREATE INDEX EMPLOYEE_EMPLOYEE_FK USING BTREE ON employee(SUPERIOR_EMP_ID);


-- deployment: Creating employee.EMPLOYEE_EMPLOYEE_FK...
ALTER TABLE employee
    ADD CONSTRAINT EMPLOYEE_EMPLOYEE_FK FOREIGN KEY (SUPERIOR_EMP_ID)
    REFERENCES employee(EMP_ID);


-- deployment: Creating employee.EMPLOYEE_DEPARTMENT_FK...
CREATE INDEX EMPLOYEE_DEPARTMENT_FK USING BTREE ON employee(DEPT_ID);


-- deployment: Creating employee.EMPLOYEE_BRANCH_FK...
CREATE INDEX EMPLOYEE_BRANCH_FK USING BTREE ON employee(ASSIGNED_BRANCH_ID);


-- deployment: Creating branch...
CREATE TABLE branch (
    BRANCH_ID int NOT NULL,
    ADDRESS varchar(30) NULL,
    CITY varchar(20) NULL,
    NAME varchar(20) NOT NULL,
    STATE varchar(10) NULL,
    ZIP_CODE varchar(12) NULL
);
ALTER TABLE branch ADD PRIMARY KEY (BRANCH_ID);


-- deployment: Creating employee.EMPLOYEE_BRANCH_FK...
ALTER TABLE employee
    ADD CONSTRAINT EMPLOYEE_BRANCH_FK FOREIGN KEY (ASSIGNED_BRANCH_ID)
    REFERENCES branch(BRANCH_ID);


-- deployment: Creating account.ACCOUNT_BRANCH_FK...
ALTER TABLE account
    ADD CONSTRAINT ACCOUNT_BRANCH_FK FOREIGN KEY (OPEN_BRANCH_ID)
    REFERENCES branch(BRANCH_ID);


-- deployment: Creating acc_transaction.ACC_TRANSACTION_BRANCH_FK...
ALTER TABLE acc_transaction
    ADD CONSTRAINT ACC_TRANSACTION_BRANCH_FK FOREIGN KEY (EXECUTION_BRANCH_ID)
    REFERENCES branch(BRANCH_ID);


-- deployment: Creating business...
CREATE TABLE business (
    INCORP_DATE date NULL,
    NAME varchar(255) NOT NULL,
    STATE_ID varchar(10) NOT NULL,
    CUST_ID int NOT NULL
);
ALTER TABLE business ADD PRIMARY KEY (CUST_ID);


-- deployment: Creating individual...
CREATE TABLE individual (
    BIRTH_DATE date NULL,
    FIRST_NAME varchar(30) NOT NULL,
    LAST_NAME varchar(30) NOT NULL,
    CUST_ID int NOT NULL
);
ALTER TABLE individual ADD PRIMARY KEY (CUST_ID);


-- deployment: Creating officer...
CREATE TABLE officer (
    OFFICER_ID int NOT NULL,
    END_DATE date NULL,
    FIRST_NAME varchar(30) NOT NULL,
    LAST_NAME varchar(30) NOT NULL,
    START_DATE date NOT NULL,
    TITLE varchar(20) NULL,
    CUST_ID int NULL
);
ALTER TABLE officer ADD PRIMARY KEY (OFFICER_ID);


-- deployment: Creating officer.OFFICER_CUSTOMER_FK...
CREATE INDEX OFFICER_CUSTOMER_FK USING BTREE ON officer(CUST_ID);


-- deployment: Creating customer...
CREATE TABLE customer (
    CUST_ID int NOT NULL,
    ADDRESS varchar(30) NULL,
    CITY varchar(20) NULL,
    CUST_TYPE_CD varchar(1) NOT NULL,
    FED_ID varchar(12) NOT NULL,
    POSTAL_CODE varchar(10) NULL,
    STATE varchar(20) NULL
);
ALTER TABLE customer ADD PRIMARY KEY (CUST_ID);


-- deployment: Creating officer.OFFICER_CUSTOMER_FK...
ALTER TABLE officer
    ADD CONSTRAINT OFFICER_CUSTOMER_FK FOREIGN KEY (CUST_ID)
    REFERENCES customer(CUST_ID);


-- deployment: Creating individual.INDIVIDUAL_CUSTOMER_FK...
ALTER TABLE individual
    ADD CONSTRAINT INDIVIDUAL_CUSTOMER_FK FOREIGN KEY (CUST_ID)
    REFERENCES customer(CUST_ID);


-- deployment: Creating business.BUSINESS_EMPLOYEE_FK...
ALTER TABLE business
    ADD CONSTRAINT BUSINESS_EMPLOYEE_FK FOREIGN KEY (CUST_ID)
    REFERENCES customer(CUST_ID);


-- deployment: Creating account.ACCOUNT_CUSTOMER_FK...
ALTER TABLE account
    ADD CONSTRAINT ACCOUNT_CUSTOMER_FK FOREIGN KEY (CUST_ID)
    REFERENCES customer(CUST_ID);


-- deployment: Creating department...
CREATE TABLE department (
    DEPT_ID int NOT NULL,
    NAME varchar(20) NOT NULL
);
ALTER TABLE department ADD PRIMARY KEY (DEPT_ID);


-- deployment: Creating employee.EMPLOYEE_DEPARTMENT_FK...
ALTER TABLE employee
    ADD CONSTRAINT EMPLOYEE_DEPARTMENT_FK FOREIGN KEY (DEPT_ID)
    REFERENCES department(DEPT_ID);


-- deployment: Creating product...
CREATE TABLE product (
    PRODUCT_CD varchar(10) NOT NULL,
    DATE_OFFERED date NULL,
    DATE_RETIRED date NULL,
    NAME varchar(50) NOT NULL,
    PRODUCT_TYPE_CD varchar(255) NULL
);
ALTER TABLE product ADD PRIMARY KEY (PRODUCT_CD);


-- deployment: Creating account.ACCOUNT_PRODUCT_FK...
ALTER TABLE account
    ADD CONSTRAINT ACCOUNT_PRODUCT_FK FOREIGN KEY (PRODUCT_CD)
    REFERENCES product(PRODUCT_CD);


-- deployment: Creating product.PRODUCT_PRODUCT_TYPE_FK...
CREATE INDEX PRODUCT_PRODUCT_TYPE_FK USING BTREE ON product(PRODUCT_TYPE_CD);


-- deployment: Creating product_type...
CREATE TABLE product_type (
    PRODUCT_TYPE_CD varchar(255) NOT NULL,
    NAME varchar(50) NULL
);
ALTER TABLE product_type ADD PRIMARY KEY (PRODUCT_TYPE_CD);


-- deployment: Creating product.PRODUCT_PRODUCT_TYPE_FK...
ALTER TABLE product
    ADD CONSTRAINT PRODUCT_PRODUCT_TYPE_FK FOREIGN KEY (PRODUCT_TYPE_CD)
    REFERENCES product_type(PRODUCT_TYPE_CD);


-- deployment: Creating contacts...
CREATE TABLE contacts (
    ID int NOT NULL,
    first_name varchar(128) NULL,
    last_name varchar(128) NULL,
    gender varchar(128) NULL,
    address_line_1 varchar(128) NULL,
    address_line_2 varchar(128) NULL,
    city varchar(128) NULL,
    postcode varchar(128) NULL,
    phone int NULL,
    email varchar(128) NULL
);


-- deployment: Creating uselessview...
CREATE VIEW uselessview AS select `moviesdev`.`contacts`.`ID` AS `ID`,`moviesdev`.`contacts`.`first_name` AS `first_name`,`moviesdev`.`contacts`.`last_name` AS `last_name`,`moviesdev`.`contacts`.`gender` AS `gender`,`moviesdev`.`contacts`.`address_line_1` AS `address_line_1`,`moviesdev`.`contacts`.`address_line_2` AS `address_line_2`,`moviesdev`.`contacts`.`city` AS `city`,`moviesdev`.`contacts`.`postcode` AS `postcode`,`moviesdev`.`contacts`.`phone` AS `phone`,`moviesdev`.`contacts`.`email` AS `email` from `moviesdev`.`contacts`;


-- deployment: Creating salesteam...
CREATE TABLE salesteam (
    ID int NOT NULL
);


-- deployment: Creating locations...
CREATE TABLE locations (
    ID int NOT NULL
);


-- deployment: Creating departments...
CREATE TABLE departments (
    ID int NOT NULL
);

