-- Script generated by Redgate Compare v1.15.2.10683


-- deployment: Dropping GetContacts...
DROP PROCEDURE GetContacts;


-- deployment: Creating GetContacts...
CREATE PROCEDURE GetContacts ()
BEGIN   
        SELECT * FROM CONTACTS;
#V3
END;


-- deployment: Altering uselessview...
CREATE OR REPLACE VIEW uselessview AS select `contacts`.`ID` AS `ID`,`contacts`.`first_name` AS `first_name`,`contacts`.`last_name` AS `last_name`,`contacts`.`address_line_1` AS `address_line_1`,`contacts`.`address_line_2` AS `address_line_2`,`contacts`.`city` AS `city`,`contacts`.`postcode` AS `postcode`,`contacts`.`phone` AS `phone`,`contacts`.`email` AS `email` from `contacts`;

